package com.main.sugarbreak.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006C49)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF10B981)
val onPrimaryContainerLight = Color(0xFF00422B)
val secondaryLight = Color(0xFF00668A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF40C2FD)
val onSecondaryContainerLight = Color(0xFF004D6A)
val tertiaryLight = Color(0xFF944A00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFEF8933)
val onTertiaryContainerLight = Color(0xFF5C2C00)
val errorLight = Color(0xFFBA1A1A)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorLight = Color(0xFFFFFFFF)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF111C2D)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF111C2D)
val surfaceVariantLight = Color(0xFFD8E3FB)
val onSurfaceVariantLight = Color(0xFF3C4A42)
val outlineLight = Color(0xFF6C7A71)
val outlineVariantLight = Color(0xFFBBCABF)

// Dark Theme Colors
val primaryDark = Color(0xFF10B981)
val onPrimaryDark = Color(0xFF022C1E)
val primaryContainerDark = Color(0xFF064E3B)
val onPrimaryContainerDark = Color(0xFF6EE7B7)
val secondaryDark = Color(0xFF38BDF8)
val onSecondaryDark = Color(0xFF003348)
val secondaryContainerDark = Color(0xFF0284C7)
val onSecondaryContainerDark = Color(0xFFCBE6FD)
val tertiaryDark = Color(0xFFF59E0B)
val onTertiaryDark = Color(0xFF451A03)
val tertiaryContainerDark = Color(0xFF78350F)
val onTertiaryContainerDark = Color(0xFFFDE68A)
val errorDark = Color(0xFFFFB4AB)
val errorContainerDark = Color(0xFF93000A)
val onErrorDark = Color(0xFF690005)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0A0F14)
val onBackgroundDark = Color(0xFFF8FAFC)
val surfaceDark = Color(0xFF0D151C)
val onSurfaceDark = Color(0xFFF8FAFC)
val surfaceVariantDark = Color(0xFF121C24)
val onSurfaceVariantDark = Color(0xFF94A3B8)
val outlineDark = Color(0xFF64748B)
val outlineVariantDark = Color(0xFF334155)

// Calendar & Habit Semantic Colors
val calendarSuccessLight = Color(0xFF006C49)
val onCalendarSuccessLight = Color(0xFFFFFFFF)
val calendarSuccessDark = Color(0xFF10B981)
val onCalendarSuccessDark = Color(0xFF022C1E)

val calendarSlipContainerLight = Color(0xFFFFEDD5)
val calendarSlipContentLight = Color(0xFFC2410C)
val calendarSlipBorderLight = Color(0xFFFDBA74)
val calendarSlipContainerDark = Color(0x40F59E0B) // amber-500 @ 25%
val calendarSlipContentDark = Color(0xFFFCD34D)
val calendarSlipBorderDark = Color(0x66F59E0B)

val calendarRestContainerLight = Color(0xFFF1F5F9)
val calendarRestContentLight = Color(0xFF475569)
val calendarRestBorderLight = Color(0xFFCBD5E1)
val calendarRestContainerDark = Color(0xCC1E293B) // slate-800 @ 80%
val calendarRestContentDark = Color(0xFFCBD5E1)
val calendarRestBorderDark = Color(0x99334155)

val calendarPendingBorderLight = Color(0xFFCBD5E1)
val calendarPendingContentLight = Color(0xFF64748B)
val calendarPendingBorderDark = Color(0xFF334155)
val calendarPendingContentDark = Color(0xFF64748B)